### ISSUE TITLE
 ffmpeg-mosaic "One or more invalid inputs."

### ISSUE THREAD

**Issue by moeC137** [woodruffw/snippets#5]
doing this:
ruby ffmpeg-mosaic 1000x1000 10x10 mosaic.mp4 $(shuf -e -n 100 300x300/*.mp4)
gives me this error:
One or more invalid inputs.

I am trying this on Linux and my .mp4 videos are in the same folder

**Comment by woodruffw** [comment]
Here's the offending line:

```ruby
abort "One or more invalid inputs." unless !inputs.empty? && inputs.all? { |i| File.file?(i) }
```

So the problem here is that your `shuf` expansion isn't producing a list of filepaths that the script can find.

**Comment by moeC137** [comment]
How could i just choose all *.mp4 in the folder? I dont need them to be random.

**Comment by moeC137** [comment]
running
`ruby ffmpeg-mosaic 1000x1000 10x10 mosaic.mp4 $(shuf -e -n 100 *.mp4)`
gave me this error:
`ffmpeg-mosaic:45:in `<main>': can't modify frozen String: "" (FrozenError)`

trying `shuf -e -n 100 *.mp4 `itself gives me a filelist tho

**Comment by woodruffw** [comment]
Ah, that might be my fault -- looks like that script got linted and had `frozen_string_literal: true` added to it even though it relies on non-frozen strings. I'll make a fix this afternoon/evening.

**Comment by moeC137** [comment]
Removing the `#frozen_string_literal: true` one line 2 actually made it work, thx so much for the help

**Comment by woodruffw** [comment]
Glad it's working for you with that change! I'll make the more permanent fix later.
